Metrics | Weather App
jasonfelice/Metrics-Weather pull request #1
Opened 2022-06-23 17:09 UTC by jasonfelice

### Weather App

- [ ] Built `Header`, `Country`, `City`, & `Heading` component.
- [ ] Created a Home page with a list of countries that could be filtered by region.
- [ ] Created a Cities page that loads a list of cities for the selected country.
- [ ] Created a Details page where the weather data loads from the API.
- [ ] Styled everything with `scss`.

2022-06-23 18:02 UTC, AmaduKamara requested changes
# Status: Required Changes ♻️♻️♻️ 

Hi @jasonfelice, 

![AlonzoLeroneThisCloseGIF (2)](https://user-images.githubusercontent.com/50941074/175364367-bc1d5960-a1ab-4c9c-8d3c-f2a729645ae4.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✅ Correct use of Gitflow
✅ No linter error
✅ Good commit messages👍
✅ Good descriptive PR 👍 
✅ App is hosted correctly and works fine 👍

## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly add a presentation video to your README as instructed in the inline comments below
- [ ] Please give credit to the design creator. He did a lot of work making that design that thousands of students are using as inspiration. He deserves credit. Please do 👍
- [ ] For this capstone project, you are required to write unit tests for your components. Kindly write a test for your project with React testing library.
- 
![image](https://user-images.githubusercontent.com/50941074/175363688-9fe5cf14-3fe4-4926-9f61-94ee73690bc3.png)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-06-23 18:02 UTC, AmaduKamara commented on README.md
> +[Preview](https://venerable-cranachan-299537.netlify.app/)
- [ ] Kindly add a video presenting your project. You are required to record a video on Loom that is at most 5 minutes long explaining the features of the app you built and also a section of your code you are most proud of implementing. Kindly record the video and app the link to the video below this hosted demo link so the next reviewer would be able to watch it.

NOTE: 
- The length of the video is 5 minutes max
- Explain what the project is about
- Explain features of the project by clicking different sections of the app and explaining things
- Lastly, Explain a section of your code you are most proud of.

- [ ] Also you are required to give credit to Nelson Sakwa for his design that was given to you as inspiration. Kindly mention and give credit to the original design creator and the design itself. Here is the link to the [original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs))

2022-06-23 18:09 UTC, jasonfelice commented
Thanks for the review @AmaduKamara.

2022-06-24 12:29 UTC, t-yanick approved these changes
Hi @jasonfelice, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-24 12:35 UTC, merged